modules_dir = "artifacts/"

[[module]]
    name = "ceramic_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    ceramic = "/root/.nvm/versions/node/v14.17.0/bin/ceramic"

[[module]]
    name = "aggregatorservice"
    # logger_enabled = true
